### ISSUE TITLE
But Cant we change the filetype via js check and upload php files on temp folder?

### ISSUE THREAD

**Issue by purnendudash** [edu-sharing/moodle-assignsubmission_edusharing#3]
But Cant we change the filetype via js check and upload php files on temp folder?

_Originally posted by @purnendudash in https://github.com/edu-sharing/moodle-assignsubmission_edusharing/issues/2#issuecomment-2007054446_

**Comment by zieglermarian** [comment]
Hi Purnendu,

This should be impossible, as a) the mime type "application/x-httpd-php" is not supported by our Edu-Sharing repositories (the DMS whence the files are uploaded to moodle) and b) we use the moodle standard file storage and file functionalities which already sanitize file uploads.

However, i added an additional check in our code in order to add redundancy. Better safe than sorry :)

Regards, Marian
